import React from "react";
import * as Icons from "lucide-react";
import { Plus, Trash2, Copy, GripVertical } from "lucide-react";

const ICON_CATEGORIES = [
  { name: "常用", icons: [["UserRound","个人"],["Contact","联系"],["Target","目标"],["Star","重点"],["BadgeCheck","认证"],["Sparkles","亮点"],["Zap","能力"],["Info","信息"]] },
  { name: "教育", icons: [["GraduationCap","学历"],["School","学校"],["BookOpen","课程"],["Library","知识"],["NotebookTabs","成绩"],["BookMarked","学习"],["Microscope","科研"],["Languages","语言"]] },
  { name: "工作", icons: [["BriefcaseBusiness","工作"],["Briefcase","职位"],["Building2","公司"],["Users","团队"],["Handshake","合作"],["Network","组织"],["Badge","职级"]] },
  { name: "项目", icons: [["FolderKanban","项目"],["FolderOpen","作品"],["Layers3","架构"],["Code2","代码"],["Rocket","上线"],["Boxes","产品"],["GitBranch","分支"],["Workflow","流程"]] },
  { name: "技能", icons: [["Code","编程"],["CodeXml","前端"],["Terminal","终端"],["Cpu","技术"],["Wrench","工具"],["Palette","设计"],["Figma","设计工具"],["Database","数据库"],["Server","服务器"],["Cloud","云服务"],["ChartNoAxesCombined","数据"]] },
  { name: "证书荣誉", icons: [["Award","荣誉"],["Trophy","奖项"],["Medal","奖牌"],["Badge","证书"],["Ribbon","认证"],["Crown","优秀"],["CheckCircle2","通过"]] },
  { name: "联系方式", icons: [["MapPin","地点"],["Phone","电话"],["Mail","邮箱"],["Globe","网站"],["Link2","链接"],["CalendarDays","时间"],["MessageCircle","沟通"],["QrCode","二维码"]] },
  { name: "校园生活", icons: [["UsersRound","社团"],["HeartHandshake","志愿"],["Megaphone","活动"],["Flag","经历"],["Landmark","校园"],["Music","文艺"],["Camera","摄影"],["Dumbbell","运动"],["Gamepad2","兴趣"]] },
  { name: "更多", icons: [["Lightbulb","创意"],["Quote","评价"],["FileText","文档"],["ClipboardList","清单"],["ListChecks","成果"],["Presentation","汇报"],["Accessibility","服务"],["Home","主页"]] },
];
const ALL_ICONS = Array.from(new Map(ICON_CATEGORIES.flatMap((c) => c.icons).map((x) => [x[0], x[1]])).entries());

const ARRAY_CONFIG = {
  education: { key: "education", title: "教育经历", create: () => ({ id:`edu-${Date.now()}`, school:"", major:"", degree:"", start:"", end:"", description:"" }) },
  experience: { key: "experience", title: "工作经历", create: () => ({ id:`exp-${Date.now()}`, company:"", position:"", start:"", end:"", description:"", achievements:[] }) },
  projects: { key: "projects", title: "项目经历", create: () => ({ id:`project-${Date.now()}`, name:"", role:"", start:"", end:"", description:"", technologies:[] }) },
  skills: { key: "skills", title: "专业技能", create: () => ({ id:`skill-${Date.now()}`, name:"" }) },
};

export default function SectionEditor({ section, resume, onResumeChange, onSectionChange }) {
  const [iconPickerOpen, setIconPickerOpen] = React.useState(false);
  const [iconSearch, setIconSearch] = React.useState("");
  const patch = (key, value) => onSectionChange({ [key]: value });
  const replaceArray = (key, index, value) => { const arr = [...(resume[key] || [])]; arr[index] = { ...arr[index], ...value }; onResumeChange({ [key]: arr }); };
  const addArrayItem = (key) => { const config = ARRAY_CONFIG[key]; if (!config) return; onResumeChange({ [key]: [...(resume[key] || []), config.create()] }); };
  const removeArrayItem = (key, index) => onResumeChange({ [key]: (resume[key] || []).filter((_, i) => i !== index) });
  const duplicateArrayItem = (key, index) => { const arr = [...(resume[key] || [])]; const copy = { ...arr[index], id:`${key}-${Date.now()}` }; onResumeChange({ [key]: [...arr.slice(0,index+1), copy, ...arr.slice(index+1)] }); };
  if (!section) return <div className="text-xs text-slate-400">从左侧选择一个模块。</div>;

  const IconComponent = Icons[section.icon] || Icons.Sparkles;
  const normalizedSearch = iconSearch.trim().toLowerCase();
  const filteredIcons = ALL_ICONS.filter(([name,label]) => `${name} ${label}`.toLowerCase().includes(normalizedSearch));

  return <div className="space-y-4">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-slate-100"><IconComponent size={16}/></div><div><div className="text-xs font-semibold">{section.title || "未命名模块"}</div><div className="text-[9px] text-slate-400">模块设置</div></div></div><label className="flex items-center gap-1 text-[10px] text-slate-500"><input type="checkbox" checked={section.visible !== false} onChange={(e)=>patch("visible",e.target.checked)}/>显示</label></div>

    <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><div className="mb-2 flex items-center justify-between"><div><div className="text-[11px] font-semibold text-slate-800">模块图标</div><div className="text-[9px] text-slate-400">选择后立即同步。</div></div><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-white shadow-sm"><IconComponent size={17}/></div></div><button type="button" className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-left text-[10px] font-medium text-slate-600" onClick={()=>setIconPickerOpen(v=>!v)}>{iconPickerOpen ? "收起图标选择器" : "更换图标"}</button>{iconPickerOpen && <div className="mt-3 rounded-xl border border-slate-200 bg-white p-2"><input className="input" placeholder="搜索图标，例如 Code / Award" value={iconSearch} onChange={(e)=>setIconSearch(e.target.value)}/><div className="mt-3 max-h-[300px] space-y-3 overflow-auto pr-1">{(normalizedSearch ? [[`搜索结果 · ${filteredIcons.length}`,filteredIcons]] : ICON_CATEGORIES.map(c=>[c.name,c.icons])).map(([title,icons])=><IconGrid key={title} title={title} icons={icons} selected={section.icon} onSelect={(name)=>{patch("icon",name);setIconPickerOpen(false);setIconSearch("");}}/> )}</div></div>}</div>

    <label className="block text-[11px] text-slate-500">模块标题<input className="input mt-1" value={section.title || ""} onChange={(e)=>patch("title",e.target.value)}/></label>
    <label className="block text-[11px] text-slate-500">标题颜色<input className="input mt-1 h-9 p-1" type="color" value={section.color || "#111827"} onChange={(e)=>patch("color",e.target.value)}/></label>

    {section.type === "summary" && <label className="block text-[11px] text-slate-500">简介内容<textarea className="input mt-1 min-h-[150px] resize-y" value={resume?.profile?.summary || ""} placeholder="请输入个人简介" onChange={(e)=>onResumeChange({ profile: { ...(resume.profile || {}), summary: e.target.value } })}/></label>}

    
    {section.type === "education" && <ArrayEditor title="教育经历" items={resume.education || []} onAdd={()=>addArrayItem("education")} onRemove={(i)=>removeArrayItem("education",i)} onDuplicate={(i)=>duplicateArrayItem("education",i)} render={(item,index)=><><input className="input mb-2" value={item.school||""} placeholder="学校" onChange={(e)=>replaceArray("education",index,{school:e.target.value})}/><div className="mb-2 grid grid-cols-2 gap-2"><input className="input" value={item.major||""} placeholder="专业" onChange={(e)=>replaceArray("education",index,{major:e.target.value})}/><input className="input" value={item.degree||""} placeholder="学历" onChange={(e)=>replaceArray("education",index,{degree:e.target.value})}/></div><div className="mb-2 grid grid-cols-2 gap-2"><input className="input" value={item.start||""} placeholder="开始" onChange={(e)=>replaceArray("education",index,{start:e.target.value})}/><input className="input" value={item.end||""} placeholder="结束" onChange={(e)=>replaceArray("education",index,{end:e.target.value})}/></div><textarea className="input min-h-[70px]" value={item.description||""} placeholder="课程 / 学习经历" onChange={(e)=>replaceArray("education",index,{description:e.target.value})}/></>}/> }
    {section.type === "experience" && <ArrayEditor title="工作经历" items={resume.experience || []} onAdd={()=>addArrayItem("experience")} onRemove={(i)=>removeArrayItem("experience",i)} onDuplicate={(i)=>duplicateArrayItem("experience",i)} render={(item,index)=><><input className="input mb-2" value={item.company||""} placeholder="公司" onChange={(e)=>replaceArray("experience",index,{company:e.target.value})}/><input className="input mb-2" value={item.position||""} placeholder="职位" onChange={(e)=>replaceArray("experience",index,{position:e.target.value})}/><div className="mb-2 grid grid-cols-2 gap-2"><input className="input" value={item.start||""} placeholder="开始" onChange={(e)=>replaceArray("experience",index,{start:e.target.value})}/><input className="input" value={item.end||""} placeholder="结束" onChange={(e)=>replaceArray("experience",index,{end:e.target.value})}/></div><textarea className="input mb-2 min-h-[80px]" value={item.description||""} placeholder="工作描述" onChange={(e)=>replaceArray("experience",index,{description:e.target.value})}/><textarea className="input min-h-[90px]" value={(item.achievements||[]).join("\n")} placeholder="每行一条工作成果" onChange={(e)=>replaceArray("experience",index,{achievements:e.target.value.split("\n").filter(Boolean)})}/></>}/> }
    {section.type === "projects" && <ArrayEditor title="项目经历" items={resume.projects || []} onAdd={()=>addArrayItem("projects")} onRemove={(i)=>removeArrayItem("projects",i)} onDuplicate={(i)=>duplicateArrayItem("projects",i)} render={(item,index)=><><input className="input mb-2" value={item.name||""} placeholder="项目名称" onChange={(e)=>replaceArray("projects",index,{name:e.target.value})}/><div className="mb-2 grid grid-cols-2 gap-2"><input className="input" value={item.role||""} placeholder="角色" onChange={(e)=>replaceArray("projects",index,{role:e.target.value})}/><input className="input" value={item.start||""} placeholder="开始" onChange={(e)=>replaceArray("projects",index,{start:e.target.value})}/></div><input className="input mb-2" value={item.end||""} placeholder="结束" onChange={(e)=>replaceArray("projects",index,{end:e.target.value})}/><textarea className="input mb-2 min-h-[85px]" value={item.description||""} placeholder="项目描述" onChange={(e)=>replaceArray("projects",index,{description:e.target.value})}/><input className="input" value={(item.technologies||[]).join(", ")} placeholder="技术栈，用逗号分隔" onChange={(e)=>replaceArray("projects",index,{technologies:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)})}/></>}/> }
    {section.type === "skills" && <ArrayEditor title="专业技能" items={resume.skills || []} onAdd={()=>addArrayItem("skills")} onRemove={(i)=>removeArrayItem("skills",i)} onDuplicate={(i)=>duplicateArrayItem("skills",i)} render={(item,index)=><input className="input" value={item.name||""} placeholder={`技能 ${index+1}`} onChange={(e)=>replaceArray("skills",index,{name:e.target.value})}/>}/> }
    {section.type === "honors" && <HonorsEditor items={resume.honors || []} onChange={(items)=>onResumeChange({honors:items})}/>} 
    {!['summary','education','experience','projects','skills','honors'].includes(section.type) && <GenericEditor section={section} patch={patch}/>} 

    <div className="rounded-xl bg-slate-50 p-3 text-[10px] leading-5 text-slate-500">每个经历模块都支持无限添加、复制和删除。左侧模块本身仍可拖动排序。</div>
  </div>;
}

function ArrayEditor({title,items,onAdd,onRemove,onDuplicate,render}) { return <div className="space-y-3"><div className="module-editor-toolbar"><span>{title} · {items.length} 条</span><button type="button" className="premium-add-btn" onClick={onAdd}><Plus size={13}/>添加{title.replace("经历","").replace("专业技能","技能")}</button></div>{items.map((item,index)=><div key={item.id||index} className="repeat-item"><div className="repeat-item-head"><span><GripVertical size={12}/> {title} #{index+1}</span><div><button type="button" className="mini-action" onClick={()=>onDuplicate(index)} title="复制"><Copy size={12}/></button><button type="button" className="mini-action danger" onClick={()=>onRemove(index)} title="删除"><Trash2 size={12}/></button></div></div>{render(item,index)}</div>)}{!items.length&&<div className="empty-inline">还没有内容，点击“添加”创建第一条。</div>}</div>; }
function HonorsEditor({items,onChange}) { const update=(i,v)=>onChange(items.map((x,n)=>n===i?v:x)); return <div className="space-y-2"><div className="module-editor-toolbar"><span>荣誉 / 证书 · {items.length} 条</span><button type="button" className="premium-add-btn" onClick={()=>onChange([...items,"新证书 / 荣誉"])}><Plus size={13}/>添加证书</button></div>{items.map((item,index)=><div key={index} className="repeat-item compact"><div className="flex items-center gap-2"><input className="input" value={item} onChange={(e)=>update(index,e.target.value)}/><button type="button" className="mini-action danger" onClick={()=>onChange(items.filter((_,i)=>i!==index))}><Trash2 size={12}/></button></div></div>)}</div>; }
function GenericEditor({section,patch}) { const items=Array.isArray(section.contentItems)?section.contentItems:section.content?[section.content]:[]; const update=(next)=>patch("contentItems",next); return <div className="space-y-2"><div className="module-editor-toolbar"><span>模块内容 · {items.length} 条</span><button type="button" className="premium-add-btn" onClick={()=>update([...items,"新内容"])}><Plus size={13}/>添加内容</button></div>{items.map((item,index)=><div key={index} className="repeat-item compact"><div className="flex items-start gap-2"><textarea className="input min-h-[62px]" value={item} onChange={(e)=>update(items.map((x,i)=>i===index?e.target.value:x))}/><button type="button" className="mini-action danger" onClick={()=>update(items.filter((_,i)=>i!==index))}><Trash2 size={12}/></button></div></div>)}{!items.length&&<div className="empty-inline">点击“添加内容”开始编辑。</div>}</div>; }
function IconGrid({title,icons,selected,onSelect}) { return <div><div className="mb-2 text-[10px] font-semibold text-slate-500">{title}</div><div className="section-icon-grid">{icons.map(([name,label])=>{const Icon=Icons[name]||Icons.Sparkles;return <button type="button" key={name} className={`section-icon-option ${selected===name?"active":""}`} title={`${label} · ${name}`} onClick={()=>onSelect(name)}><span className="section-icon-option-icon"><Icon size={16}/></span><span>{label}</span></button>})}</div></div>; }
